name: Check PHP Syntax

on:
  push:
    branches:
      - main
      - Pagina-Inicial
      - backend
      
  pull_request:
    branches:
      - main

jobs:
  check-php-syntax:
    name: Check PHP Syntax
    runs-on: ubuntu-latest
    steps:
      -
        name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          # This is the minimum PHP version supported by your project
          php-version: '8.2'
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          directory: .
